# Generated by Django 4.2 on 2024-09-13 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminapp", "0001_initial"),
        ("userapp", "0002_attendee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("post_img", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.category",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "post",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "tag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=500)),
                ("thread_img", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentapp.post",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "thread",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ThreadTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contentapp.tag"
                    ),
                ),
                (
                    "thread_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentapp.thread",
                    ),
                ),
            ],
            options={
                "db_table": "thread_tag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentapp.post",
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contentapp.tag"
                    ),
                ),
            ],
            options={
                "db_table": "post_tag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentapp.post",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "post_like",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentapp.post",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "managed": True,
            },
        ),
    ]
