# Generated by Django 4.2 on 2024-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0005_rename_thread_img_thread_img_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contents",
            name="img_url",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="img_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
