server:
  port: 8080

springdoc:
  swagger-ui:
    path:/swagger-ui.html

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

spring:
  profiles:
    default: development

--- # development phase
spring:
  config:
    activate:
      on-profile: development

  auth-server:
    url: ${AUTH_SERVER_URL}

  datasource:
    url: jdbc:${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2-console

--- # production phase
spring:
  config:
    activate:
      on-profile: production

  auth-server:
    url: ${AUTH_SERVER_URL}

  datasource:
    url: jdbc:${DATABASE_URL}/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
