springdoc:
  swagger-ui:
    path:/swagger-ui.html

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

--- # development phase
spring:
  profiles:
    active: development

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2-console


--- # alpha phase
spring:
  config:
    activate:
      on-profile: alpha

  datasource:
    url: jdbc:h2:file:./db/alpha
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2-console
