# Generated by Django 4.2 on 2024-09-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=50)),
            ],
            options={
                "db_table": "category",
                "managed": True,
            },
        ),
    ]
