# Generated by Django 4.2 on 2024-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="img_url",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
