# Generated by Django 4.2 on 2024-09-20 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contentapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nick_name", models.CharField(max_length=100, null=True)),
                ("profile_img", models.CharField(max_length=200, null=True)),
                ("user_id", models.BigIntegerField()),
                ("self_introduction", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "follower_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower",
                        to="userapp.profile",
                    ),
                ),
                (
                    "following_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "follow",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "content_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contentapp.contents",
                    ),
                ),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "attendee",
                "managed": True,
            },
        ),
    ]
