# Generated by Django 4.2 on 2024-09-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_img",
            new_name="img_url",
        ),
    ]
