# Generated by Django 4.2 on 2024-09-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userapp.profile",
                    ),
                ),
            ],
            options={
                "db_table": "attendee",
                "managed": True,
            },
        ),
    ]
