# Generated by Django 4.2 on 2024-09-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0001_initial"),
        ("userapp", "0002_attendee"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="post_id",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="contentapp.post",
            ),
            preserve_default=False,
        ),
    ]
