# Generated by Django 4.2 on 2024-09-24 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0005_rename_thread_img_thread_img_url_and_more"),
        ("userapp", "0003_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="content_id",
            field=models.ForeignKey(
                db_column="content_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="contentapp.contents",
            ),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="profile_id",
            field=models.ForeignKey(
                db_column="profile_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="userapp.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower_user_id",
            field=models.ForeignKey(
                db_column="follower_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to="userapp.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="following_user_id",
            field=models.ForeignKey(
                db_column="following_user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="userapp.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="self_introduction",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
