# Generated by Django 4.2 on 2024-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userapp",
            "0004_alter_attendee_content_id_alter_attendee_profile_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
